model_params:
  name: 'BetaVAE'
  in_channels: 1
  latent_dim: 128
  loss_type: 'B'
  beta: 10.

exp_params:
  dataset: shapes
  data_path: "dataset/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 3
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_B"
  manual_seed: 1265